baseURL = "https://www.conall.net/"
languageCode = "en-ie"
theme = "hello-friend-ng"

googleAnalytics = "UA-128676-5"
title = "Conall O'Brien"

# Bio
# TODO(conall): Get the subtitle to work
sub = "Testing 123"
# "https://www.untappd.com/user/conall/"  

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  keywords = "homepage, blog, personal, personal branding"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  hideCredits = true
  hideCopyright = false

  sharing = true

  #
  # Page Content
  # 

  author = "Conall O'Brien"

  # Photo
# TODO(conall): Get the profile photo to work
  avatar = "content/DSC02070.smaller.jpg"

  # Social Media
  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/conallob"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/conall0b"
  [[params.social]]
    name = "twitter"
    url = "https://www.twitter.com/conall"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/conall/"  
  [[params.social]]
    name = "keybase"
    url = "https://www.keybase.io/conall"
  [[params.social]]
    name = "github"
    url = "https://github.com/conallob"
  [[params.social]]
    name = "email"
    link = "mailto:conall@conall.net"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blog.conall.net"
