baseURL = "https://www.conall.net/"
# Force https
canonifyURLs = true
enforce_ssl = "www.conall.net"

languageCode = "en-ie"
theme = "hello-friend-ng"

title = "Conall O'Brien"

[services]
  [services.googleAnalytics]
    ID = 'G-MDG8SMJ0J2'

# Bio
# "https://www.untappd.com/user/conall/"  

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  keywords = "homepage, blog, personal, personal branding"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  hideCredits = true
  hideCopyright = false

  sharing = true

  #
  # Page Content
  # 

  name = "Conall O'Brien"
  aboutMe = [
    "Husband, Father of 2",
    "Pet Human to a Cat",
    "Veteran of [Google SRE](https://landing.google.com/sre/)",
    "Tinkerer, Woodworker, Beer Nerd",
    "Internet Native, Dubliner, Traveller",
    "Wellbeing Advocate",
    "Hair Colour May Vary",
    "he/him"
  ]

  # Photo
  # TODO(conall): Fix the headshot layout, it's slightly off centre
  headshot = "headshot.jpg"

  # Social Media
  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/conallob"
    icon = "fa fa-2x fa-facebook"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/conall0b"
    icon = "fa fa-2x fa-instagram"    
  [[params.social]]
    name = "twitter"
    url = "https://www.twitter.com/conall"
    icon = "fa fa-2x fa-twitter"
  [[params.social]]
    name = "mastodon"
    url = "https://mastodon.ie/web/@conall"
    icon = "fa fa-2x fa-mastodon"
    rel = "me"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/conall/"
    icon = "fa fa-2x fa-linkedin"    
  [[params.social]]
    name = "keybase"
    url = "https://www.keybase.io/conall"
    icon = "fa fa-2x fa-keybase"    
  [[params.social]]
    name = "github"
    url = "https://github.com/conallob"
    icon = "fa fa-2x fa-github"    
  [[params.social]]
    name = "leetcode"
    url = "https://www.leetcode.com/conallob"
    icon = "fa fa-2x fa-leetcode"
  [[params.social]]
    name = "email"
    link = "mailto:conall@conall.net"
    icon = "fa fa-2x fa-paper-plane"   

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blog.conall.net"
